/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.uesocc.ingenieria.tpi135_2018.mantenimiento.vista;

import java.awt.Component;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import static java.nio.file.Files.list;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sv.edu.uesocc.ingenieria.tpi135_2018.mantenimiento.definiciones.MigracionControl;
import sv.edu.uesocc.ingenieria.tpi135_2018.mantenimiento.definiciones.MigracionHistorico;
import sv.edu.uesocc.ingenieria.tpi135_2018.mantenimiento.mantenimientodatalib.ArchivoRest;
import sv.edu.uesocc.ingenieria.tpi135_2018.mantenimiento.mantenimientodatalib.gestorArchivos;

/**
 *
 * @author joker
 */
public class vistaArchivos extends javax.swing.JFrame {

    gestorArchivos gestor = new gestorArchivos();
    DefaultListModel modelo = new DefaultListModel();    
    ArchivoRest gestoRest;
    String ruta = "";
    List<File> listaArchivos;
    private Component contentPane;

    /**
     * Creates new form vistaArchivos
     */
    public vistaArchivos() {
        initComponents();
        Limpiar();
    }
    
    public void Limpiar(){
        modelo = new DefaultListModel();
        txtRuta.setText("");
        cbxTipo.setSelectedIndex(0);
        lblSeparador.setText(",");
        txtSeparador.setEnabled(false);
        chkEncabezado.setEnabled(false);
        btnEnviar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarRuta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listArchivos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        chkEncabezado = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtSeparador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblAdvEncabezadp = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MIGRACION CSV");
        setBackground(new java.awt.Color(221, 188, 149));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(80, 81, 96));
        jPanel1.setName("Migracion CSV"); // NOI18N

        txtRuta.setBackground(new java.awt.Color(102, 165, 173));
        txtRuta.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta.setText("   ");
        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione ruta para cargar archivos");

        btnBuscarRuta.setBackground(new java.awt.Color(89, 130, 52));
        btnBuscarRuta.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnBuscarRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarRuta.setText("Cargar Archivo");
        btnBuscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutaActionPerformed(evt);
            }
        });

        listArchivos.setBackground(new java.awt.Color(102, 165, 173));
        listArchivos.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        listArchivos.setForeground(new java.awt.Color(255, 255, 255));
        listArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listArchivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listArchivos);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Archivos Cargados:");

        btnEnviar.setBackground(new java.awt.Color(89, 130, 52));
        btnEnviar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Agregar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        chkEncabezado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        chkEncabezado.setText("Contiene Encabezado");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Separador");

        txtSeparador.setBackground(new java.awt.Color(102, 165, 173));
        txtSeparador.setForeground(new java.awt.Color(255, 255, 255));
        txtSeparador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeparadorKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(89, 130, 52));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblAdvEncabezadp.setText(" ");

        lblSeparador.setForeground(java.awt.Color.red);
        lblSeparador.setText("  ");

        cbxTipo.setBackground(new java.awt.Color(102, 165, 173));
        cbxTipo.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Migracion de control", "Migracion de historico" }));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de Migracion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnBuscarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(24, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(chkEncabezado)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(353, 353, 353)
                                .addComponent(lblAdvEncabezadp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSeparador)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkEncabezado)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdvEncabezadp)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutaActionPerformed
        Limpiar();
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione el directorio de sus archivos");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(contentPane) == JFileChooser.APPROVE_OPTION) {
            ruta = chooser.getSelectedFile().getAbsolutePath();
            if (gestor.verificarDirectorio(ruta)) {
                txtRuta.setText(ruta);
                try {
                    listaArchivos = gestor.cargarArchivos(ruta);
                    for (File fil : listaArchivos) {
                        String filePath[] = fil.toString().split(ruta);
                        modelo.addElement(filePath[filePath.length-1]);                        
                    }
                    if(listaArchivos.isEmpty()){
                        JOptionPane.showMessageDialog(null, "No se encontro ningu archivo");
                    }else{
                        listArchivos.setModel(modelo);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(vistaArchivos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No selecciono ningun directorio");
        }
        
    }//GEN-LAST:event_btnBuscarRutaActionPerformed

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaActionPerformed

    private void txtSeparadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeparadorKeyTyped
        char tipe = evt.getKeyChar();
        if ((tipe < ',' || tipe > '.') && (tipe < ':' || tipe > ';')) {
            evt.consume();
        }
        if (txtSeparador.getText().length() == 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSeparadorKeyTyped

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if(!txtSeparador.getText().isEmpty()){
            gestor.setCaracter(txtSeparador.getText());
        }
        if(chkEncabezado.isSelected()){
            gestor.setEncabezado(true);
        }
        int seleccion = cbxTipo.getSelectedIndex();
        int seleccionado = listArchivos.getSelectedIndex();
        System.out.println(seleccionado);
        
        if(seleccionado >=0){
            switch(seleccion){

                case 0:
                    JOptionPane.showMessageDialog(null, "Selecciona el tipo de migracion");                
                break;
                case 1://Migracion Control
                    try {                    
                        List<List<String>> l = gestor.parser(new File(ruta+"/"+modelo.get(seleccionado).toString()));
                        List<MigracionControl> lMC = gestor.parserControl(l);
                        if(!lMC.isEmpty()){
                            modelo.remove(seleccionado);
                            listArchivos.setModel(modelo);
                            //gestoRest.postMigracionControl(lMC);
                        }else{
                            JOptionPane.showMessageDialog(null, "El archivo no coincide el tipo de migracion seleccionado");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(vistaArchivos.class.getName()).log(Level.SEVERE, null, ex);
                    }            
                break;
                case 2://Migracion Historico
                    try { 
                        List<List<String>> l = gestor.parser(new File(ruta+"/"+modelo.get(seleccionado).toString()));
                        List<MigracionHistorico> lMH = gestor.parserHistorico(l);
                        if(!lMH.isEmpty()){
                            modelo.remove(seleccionado);
                            listArchivos.setModel(modelo);
                            //gestoRest.postMigracionHistorico(lMH);
                        }else{
                            JOptionPane.showMessageDialog(null, "El archivo no coincide el tipo de migracion seleccionado");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(vistaArchivos.class.getName()).log(Level.SEVERE, null, ex);
                    }            
                break;
                default:
                break;            
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione el archivo que desea enviar"); 
        }
    }//GEN-LAST:event_btnEnviarActionPerformed


    private void listArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listArchivosMouseClicked
        txtSeparador.setEnabled(true);
        chkEncabezado.setEnabled(true);
        btnEnviar.setEnabled(true);
    }//GEN-LAST:event_listArchivosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRuta;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JCheckBox chkEncabezado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdvEncabezadp;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JList<String> listArchivos;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtSeparador;
    // End of variables declaration//GEN-END:variables
}
